### ISSUE TITLE
代码合并问题

### ISSUE THREAD

**Issue by steermomo** [kingwkb/readability#2]
很糗之前提交了一次代码，但在使用过程中发现出现了问题，比如下面的连接就提取失败
http://www.sjtu.edu.cn/xiaoli/xlactivitycontent.jsp?urltype=news.NewsContentUrl&wbtreeid=1251&wbnewsid=68183

不知道Demo 的代码更新了没

**Comment by kingwkb** [comment]
Demo 没有更新，还是老的
你看看有什么问题，修复下，最近我没时间来处理这些问题，很抱歉

**Comment by steermomo** [comment]
谢谢回复，我找找问题在哪
